### PR TITLE
Fix #26

### LINKED ISSUE #26: Failed desktop integration
Hey all,
I'm trying to install the Ubuntu version of SLiMgui using the `DebianUbuntuInstall.sh` script as described at page 61-62 of the SLiM Manual. The installation to `/usr/bin` is successful, however the desktop integration fails, due to some missing files:

```bash
Installation to /usr/bin was successful. Proceeding with desktop integration.
mv: cannot stat '../SLiM/org.messerlab.slimgui-mime.xml': No such file or directory
mv: cannot stat '../SLiM/org.messerlab.slimgui.desktop': No such file or directory
mv: cannot stat '../SLiM/org.messerlab.slimgui.appdata.xml': No such file or directory
xdg-mime: file '/usr/share/mime/packages/org.messerlab.slimgui-mime.xml' does not exist
Desktop integration failed. 
```

I tried removing the three lines from the script, but of course that's a naif solution that doesn't work since I assume they are needed in order to run `update-mime-database`. If it helps, I'm running Ubuntu 22.04, let me know if you need other information.

Any help would be great, but is not urgent - since I can open the gui through the command line. Thanks!

### PR DESCRIPTION
**Pull request by bryce-carson**
Hi Ben,

This should fix the current issues, #26 and https://github.com/MesserLab/SLiM/issues/441.

I have tested the updated script with Ubuntu 18.04.

### CODE REVIEW

**Comment by bryce-carson** [comment]
The file installation/CMakeLists.patch is unnecessary. That was included in this pull request accidentally.

**Comment by bhaller** [comment]
> The file installation/CMakeLists.patch is unnecessary. That was included in this pull request accidentally.

Hi @bryce-carson.  I'm not sure what to do with this...?  Can you remove this file from the PR?  I'm not sure how to merge the PR while excluding this file from the merge.

**Comment by bryce-carson** [comment]
> > The file installation/CMakeLists.patch is unnecessary. That was included in this pull request accidentally.
> 
> Hi @bryce-carson.  I'm not sure what to do with this...?  Can you remove this file from the PR?  I'm not sure how to merge the PR while excluding this file from the merge.

I'll see what I can do in the morning.

**Comment by bhaller** [comment]
> > > The file installation/CMakeLists.patch is unnecessary. That was included in this pull request accidentally.
> > 
> > 
> > Hi @bryce-carson.  I'm not sure what to do with this...?  Can you remove this file from the PR?  I'm not sure how to merge the PR while excluding this file from the merge.
> 
> I'll see what I can do in the morning.

I could certainly copy-paste your changes into a commit on my end, if you're not sure how to clean this up.  The change would then not be marked as originating from you, or as related to this PR, though.  Having the commit history right, for things like this, might be useful to keep us from getting confused later.  Sorry for the hassle.  I think you should be able to just remove the file on your end, `git remove` it, and push that change to GitHub to update this PR.  But I'm not sure; I'm pretty clueless with git.

**Comment by bryce-carson** [comment]
> > > > The file installation/CMakeLists.patch is unnecessary. That was included in this pull request accidentally.
> > > 
> > > 
> > > Hi @bryce-carson.  I'm not sure what to do with this...?  Can you remove this file from the PR?  I'm not sure how to merge the PR while excluding this file from the merge.
> > 
> > 
> > I'll see what I can do in the morning.
> 
> I could certainly copy-paste your changes into a commit on my end, if you're not sure how to clean this up. The change would then not be marked as originating from you, or as related to this PR, though. Having the commit history right, for things like this, might be useful to keep us from getting confused later. Sorry for the hassle. I think you should be able to just remove the file on your end, `git remove` it, and push that change to GitHub to update this PR. But I'm not sure; I'm pretty clueless with git.

Yes, I think removing the file in an additional commit and pushing it to this branch will work just fine.

**Comment by bryce-carson** [comment]
Done, @bhaller.

**Comment by bryce-carson** [comment]
If you run into any problems during the workshops, let me know. I'll do what I can in the evenings after work. It should all be fine, though; I'm just a little paranoid about the changes because I haven't tested every corner manually -- that's the problem with BASH scripting, you've got to work with an operating system rather than a single language you're testing your changes upon (at least Debian and Ubuntu are very closely related :octocat:).

**Comment by bhaller** [comment]
Thanks, merged!  :->  I'll let you know if any issues arise.  Yes, cross-platform testing is a difficult thing – for SLiMgui, too!

**Pull request merged**
