### PR TITLE
Update Windows10Installation.md

### PR DESCRIPTION
**Pull request by bryce-carson**
Finalize the instructions. Add some verbosity. Reorder the steps.

### CODE REVIEW

**Comment by bhaller** [comment]
Ready for merge?

**Comment by bryce-carson** [comment]
> Ready for merge?

Yes, it should be ready now.

Note the commit message on #5eff143:
> :warning: The GitHub Preview and rendering of this Markdown file is formatting Step 4-d correctly, despite it not having any backticks. :confused: This might cause issues later. Who knows what's happening?

**Comment by bryce-carson** [comment]
Alright. It's ready. I'm not going to push any more commits to this PR. I believe it's done. Feel free to proof-read it for me.

**Comment by bhaller** [comment]
> Note the commit message on #5eff143:
> 
> > ⚠️ The GitHub Preview and rendering of this Markdown file is formatting Step 4-d correctly, despite it not having any backticks. 😕 This might cause issues later. Who knows what's happening?

:-O

**Comment by bryce-carson** [comment]
> > Note the commit message on #5eff143:
> > > warning The GitHub Preview and rendering of this Markdown file is formatting Step 4-d correctly, despite it not having any backticks. confused This might cause issues later. Who knows what's happening?
> 
> :-O

My only guess is that indentation is important. 🤷🏻

**Pull request merged**
