### PR TITLE
Windows 10 Installation Procedure with Graphical WSL

### PR DESCRIPTION
**Pull request by bryce-carson**
This installation procedure eases setting up an XServer on Windows 10. Once WSL is installed, the overall procedure is reduced to a few clicks within the Windows Store. Then the installation procedure closely follows the Debian script, but with a couple necessary inclusions.

### CODE REVIEW

**Comment by bhaller** [comment]
This looks great.  Is it ready to merge?

**Comment by bryce-carson** [comment]
> This looks great. Is it ready to merge?

Thanks! Yes, it is ready to be merged now.

If we have some testing of this procedure, we can remove "Experimental" from the title and then include it in the SLiM manual. I can test it on a second Windows 10 machine, which does not have WSL installed yet (so it's very fresh and good for testing), and report back through email.

Otherwise, we might announce this experimental procedure in #slim-discuss, or refer to it in the manual. We might also just leave it here until we have some more testing. :octocat:

**Comment by bhaller** [comment]
> > This looks great. Is it ready to merge?
> 
> Thanks! Yes, it is ready to be merged now.

  OK, will do.

> If we have some testing of this procedure, we can remove "Experimental" from the title and then include it in the SLiM manual. I can test it on a second Windows 10 machine, which does not have WSL installed yet (so it's very fresh and good for testing), and report back through email.

OK.  I don't think we have any Windows users in the Messer Lab, but perhaps @bernard-kim would be interested in giving this a whirl?

> Otherwise, we might announce this experimental procedure in #slim-discuss, or refer to it in the manual. We might also just leave it here until we have some more testing. :octocat:

I'll merge it now, and feel free to post a message about it on slim-discuss.  Once we have the impression that people have tried it successfully, I'll add it to the manual.  Thanks!

**Comment by bernard-kim** [comment]
It works great for me, thanks @bryce-carson! One suggestion based on a quick hiccup I ran into:

In the instruction, for step 7: 

> Step 7: "Copy this information into the "VcXsrv Flags:" text field: -nowgl -compositewm -multiwindow -clipboard -primary"

add a note that the user should select the new profile to make it the active profile.

**Comment by bryce-carson** [comment]
> It works great for me, thanks @bryce-carson! One suggestion based on a quick hiccup I ran into:
> 
> In the instruction, for step 7: 
> 
> > Step 7: "Copy this information into the "VcXsrv Flags:" text field: -nowgl -compositewm -multiwindow -clipboard -primary"
> 
> add a note that the user should select the new profile to make it the active profile.
> 
> 

That's great!

Thanks for the feedback.

**Comment by bhaller** [comment]
This probably doesn't need to be marked as "experimental" now that we've got more testing on it?

**Pull request merged**
